"""empty message

Revision ID: 26257359c6e9
Revises: 8ecded4a4792
Create Date: 2022-06-15 22:09:29.060695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26257359c6e9'
down_revision = '8ecded4a4792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('password', sa.String(length=250), nullable=True))
    op.add_column('Usuario', sa.Column('email', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuario', 'email')
    op.drop_column('Usuario', 'password')
    # ### end Alembic commands ###
